# configs/qwen_sft.yaml
# Model Arguments
model_name_or_path: Qwen/Qwen3.5-0.8B
template: chatml
# Data Arguments
dataset_dir: data/mined_new/nan_eng/CP_wikiplus10_035/
dataset: poj_translation
cutoff_len: 2048
max_samples: 1000000
overwrite_cache: false
preprocessing_num_workers: 16
# Training Arguments
stage: sft
do_train: true
finetuning_type: full
learning_rate: 7.0e-05
lr_scheduler_type: cosine
num_train_epochs: 20
max_grad_norm: 1.0
weight_decay: 0.0
warmup_ratio: 0.0
# Batch size & System
per_device_train_batch_size: 8
gradient_accumulation_steps: 32
flash_attn: fa2
output_dir: checkpoints/CP_wikiplus10_035
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: false
bf16: true
resume_from_checkpoint: checkpoints/CP_wikiplus10_035/checkpoint-12500